### ISSUE TITLE
Feature request: Conditional rendering

### ISSUE THREAD

**Issue by jmz7v** [paperclip-ui/legacy-paperclip#440]
Example use case: A button with an optional icon inside, but render null/undefined if prop is not there.

PC component definition syntax idea – Keep `prop?` to indicate conditional rendering, use `&&` to indicate truthy value
```jsx
<button export component as="default" {onClick?}>
  {icon? && <Icon />}
  {children}
</button>
```

#### Usage inside React with defined `icon` (assuming `Icon` renders an img tag or whatever thing it wants)
```jsx
<Button onClick={handleClick} icon={<IconPlus />}>Add User</Button>
```
Expected output (DOM)
```jsx
<button>
  <img src="icons/plus.svg" />
  Add User
</button>
```

#### Usage inside React with no icon
```jsx
<Button onClick={handleClick}>Add User</Button>
```
Expected output (DOM)
```jsx
<button>
  Add User
</button>
```

**Comment by crcn** [comment]
What's your motivation for this? Can this behavior be achieved with preview components? Or is it that `icon` is rendered as `undefined` if it's not set? 

<img width="1054" alt="Screen Shot 2020-08-13 at 8 18 27 AM" src="https://user-images.githubusercontent.com/757408/90139246-b7865880-dd3d-11ea-844d-fed1234a364b.png">

I've been thinking about preventing `undefined` from showing up - doesn't do much except to indicate that a slot isn't set. Would that help?

**Comment by jmz7v** [comment]
Yup, pretty much.
My main motivation is that many things may or may not exist inside a component, a recent use case required me to add a list of social network icons but the profile links may or may not exist.

Example:
So I added this `<ContactLinks />` component with props like `facebook="/profileid"` and `instagram="/profileid"` but what if this account does not have a `twitter` prop, I wouldn't want this to render the twitter icon inside `ContactLinks`.

Creating `Facebook, Twitter , Instagram, LinkedIn` components and exporting them is not a problem, they could latter be passed as children to `ContactLinks` but only send those that are defined. It would be sweet to be able to send everything and have a way for PC to not render things from a falsy condition which would usually be `string.length === 0` or `value === null` or `typeof value == = "undefined"`.

**Comment by crcn** [comment]
> So I added this <ContactLinks /> component with props like facebook="/profileid" and instagram="/profileid" but what if this account does not have a twitter prop, I wouldn't want this to render the twitter icon inside ContactLinks.

Got it 👍🏻.  So this _should_ work now with the most recent release. E.g:

```html
<div export component as="ContactLinks">
  {facebook?} <!-- renders as nothing if "facebook" isn't present -->
  {twitter?}  <!-- renders as nothing if "twitter" isn't present -->
</div>

<ContactLinks facebook={<span />} /> <!-- renders: <div><span /></div> -->
<ContactLinks twitter={<br /> <!-- renders: <div><br /></div> -->
```

Additionally, you can also leverage CSS to display elements based on the given props. For example:

```html
<style>
  .contact-list {
    .facebook, .twitter {
      display: none;
    }
    
    &--has-facebook {
      .facebook {
        display: block;
      }
    }
    &--has-twitter {
      .facebook {
        display: block;
      }
    }
  }

</style>

<div export component as="ContactLinks" 
  className:facebookLink="contact-list--has-facebook" 
  className:twitterLink="contact-list--has-twitter">
  <div className="facebook">
    <a href={faebookLink?}>Do stuff</a>
  </div>
  <div className="twitter">
    <a href={twitterLink?}>Do stuff</a>
  </div>
</div>
```

Lmk if this helps!
