### ISSUE TITLE
PC files need to be compiled into intermediate format

### ISSUE THREAD

**Issue by crcn** [paperclip-ui/legacy-paperclip#873]
PC -> intermediate format -> code.

This is primarily to make it easier for creating new compilers into language targets. Reason for this is that translations will largely be similar to one another. E.g: the compiled CSS output, and the elements that use those styles. We can also compile information about props that can be used for languages that are strongly typed. 

This will also greatly simplify the React compiler.

Considerations:

- VueJS
- SvelteJS
- FFI

**Comment by just-be-dev** [comment]
Not to overly complicate the initial translation but you could reduce downstream complexity by pre-compiling specific aspects of pc files based on a given configuration. 

For example, with svelte you can largely preserve nested styles `:global` selectors, etc. When writing an HTML compiler though, nesting is an unnecessary complexity to that implementation. You could pass a compiler config that effectively disables that output (by essentially pre-compiling it)

```json
{
  "compilerOptions": {
     "nesting": false
   }
}
```

The features list would be relatively extensive and you might want to version this config, but it would _greatly_ simplify compile targets.

**Comment by crcn** [comment]
Do you mean to preserve certain language characteristics depending on the compile target? For example, given the PC style:

```html
<style>
  ul {
    font-family: Papyrus;
    margin: 0;
    padding: 0;
    li {
      list-style-type: none;
    }
  }
</style>
```

The HTML output would be:

```html
<style>
  ul {
    font-family: Papyrus;
    margin: 0;
    padding: 0;
  }

  ul li {
    list-style-type: none;
  }
</style>
```

But the Svelte CSS would essentially be the same as the source (with nesting). Using a config the developer may have some wiggle room to preserve PC language characteristics?

**Comment by just-be-dev** [comment]
Pretty much, yes. 

I see the intermediate layer as an AST. The configuration would allow disabling certain nodes of that AST from being output. I.e. nested styles in this case. The resulting AST would be a subset of the raw representation of the pc component with the appropriate transformations applied.

**Comment by crcn** [comment]
ahh got it, so more concretely something like this?

```javascript
const source = `<style>
  ul { 
    li {
       font-family: Comic Sans MS;
    }
  }
</style>`;

const intermediateAST = translateIntermediateAST(source, { nesting: true });
const svelteSource = translatePcToSvelte(intermediateAST);

const intermediateAST2 = translateIntermediateAST(source, { nesting: false });
const htmlSource = translatePcToHTML(intermediateST2);
```

☝️ just as an illustration, shooting from the hip a bit. I'd imagine that something like `translateIntermediateAST` (or whatever) would likely be embedded (along with the config passed) in the target compiler. No need to have this as a user defined config.

**Comment by just-be-dev** [comment]
Yes, exactly. The `translatePcToSvelte` and `translatePcToHTML` could ostensibly be user land printers that act on the transformed AST. You could also wrap this whole API up into a cli tool that could be invoked as a subprocess of whatever runtime language the creator of the printer wanted to use. 

Contrived example

```bash
paperclip-compile --config=paperclip.compile.json | my-svelte-printer
```

**Comment by crcn** [comment]
I wonder if this is problematic for certain cases. For example, here's a very Paperclip-y example:

```html
<!-- data-pc-label is annotation for UI editor + used for more readable style selector -->
<div data-pc-label="my element">
  <style>
    color: red;
  </style>
</div>
```

☝️ I would imagine this would have to be translated into this (which is the default output anyways):

```html
<style>
  ._059bb_my_element {
    color: red;
  }
</style>

<div class="_059bb_my_element"></div>
```

Not sure how PC can be preserved for Svelte in this case. I'd imagine here that styles would need to be translated like this. 


Another example with nested styles that might be tricky. E.g:

```html
<div export component as="Message" {className?}>
  <span className={nestedClassName}>
    {children}
  </span>
</div>
```

And then:

```html
<import src="./Message.pc" as="Message" />

<style>
  :global(div) {
    .my-nested-element {
      color: red;
    }
  }
</style>

<!-- inject style into Message -->
<Message nestedClassName="$my-nested-element">
   I'm blue text
</Message>
```

For a cleaner version:

```html
<import src="./Message.pc" as="Message" />

<!-- inject style into Message -->
<Message nestedClassName="$my-nested-element">
   <style>
      .my-nested-element {
        color: red;
      }
   </style>
   I'm blue text
</Message>
```


What do you think?

**Comment by just-be-dev** [comment]
So we're going from pc to an intermediate layer. It's still up to the consumer of that AST to interpret what code it actually needs to output.  So here's sort of what I'm thinking.

I'm going to represent the AST in [kdl](https://kdl.dev/) just for terseness and focus for a second on the first example.

```kdl
div data-pc-label="my element" {
  style {
    color "red"
  }
}
```
By default, maybe this is the raw AST output. There's no processing done here and the client can choose how to transform this into their base representation. Maybe an HTML processor decides it wants to inline the nested styles:

```html
<div data-pc-label="my element" style="color: red"> 
</div>
```

Maybe though, we provide an option to remove nesting. The challenge on paperclip's side is to determine the impacts of that option on the output AST. Perhaps your second code block is how we'd decided to do that.

```kdl
style {
  selector class="_059bb_my_element" {
    color "red"
  }
}

div data-pc-label="my element" class="_059bb_my_element"
```

Now this is an interpretation of what that transformation might look like, but at this point it's _still_ on the consumer of the AST to determine how they want this to output. Styles in svelte are scoped by default, so maybe when the translator for svelte is written it has some internal optimizations to recognize that these are the same and optimizes it away. The resulting svelte might be something like...

```svelte
<style>
div {
  color: red;
}
</style>

<div data-pc-label="my element"/>
```

Or the translator could still decide to inline it like the HTML example above. The point here is, we don't necessarily care. That's not our business. What should be our business though, is providing mechanisms to make the AST as simple as reasonably possible for translation to another target. 

I mean, the first target should be just outputting a raw AST in some consumable format. Then we can iterate on transformations that generate ASTs more optimized for various consumers.

**Comment by crcn** [comment]
Seems like the point around this is to give flexibility to the engineer around the PC output. Though, should we care about _correctness_. For example, inlined styles would introduce a behavior change since it has a different specificity. 

Regarding exposing the AST - seems like it can be simplified into something that's easier to digest - a JSON doc that has all of the info necessary to _easily_ translate into another language. For example:

```javascript
const intermittentPCModule = translateIntermittentModule(`
  <style> div { color: red; } </style>
  <div export component as="Component">
    {children}
  </div>
`);
```

Could produce something simple like:

```javascript
{
  

  // all imports into the document
  imports: [/*{ source: "./some-module.pc", namespace: "blarg"}*/]

  // the entire style sheet document
  styleSheet: [
    {  
      type: "StyleRule",
      selectorText: "_04a9d_div",
      declarations: [
        { 
      ],

      // for source maps, but this would be unnecessary for MVP. 
      source: { line: 37, column: 14 }
    }
  ],

  components: [
    {

      // for imported components
      // namespace: "blarg",
      
      name: "Component",

      // defined if `export` attribute is present
      exported: true,
      tagName: "div",
      type: "Element",
      attributes: []
      children: [
        { type: "Slot", name: "children" }
      ]
    }
  ]
}
```

☝️ looks like an AST, but not quite. We can control the shape of this too based on parameters that are passed in such as `nested: true`, to ensure that the output is always correct.  What do you think?

**Comment by crcn** [comment]
The other thing coming to mind is that we can also include all of the imported assets into this JSON file. E.g:

```javascript
{
  imports: [
    { source: "./asset.svg" }
  ]
}
```

☝️ something like this might be a good candidate for something like a `bundleAssets: true` flag, where the asset path is preserved if `false`, and bundled if `true` like so:

```javascript
{
  imports: [
    { source: "./asset.svg", output: "59bb.svg" }
  ],
  styleSheet: [
    { 
      type: "StyleRule",
      selectorText: ".test",
      declarations: [

        // value is transformed here based on `bundleAssets: true`
        { name: "background", value: "url(59bb.svg)" }
      ]
    }
  ]
}
```

👆 API could be better here. There could be an optional `assetPath` flag for this too.

**Comment by just-be-dev** [comment]
I think sourcemaps should definitely be front-loaded into the design of whatever the data structure is. Not doing so may make it hard to go back and that's an important part of the debugging experience.

**Comment by crcn** [comment]
Cool, would you prefer to write this functionality? Happy to carve out some space for you. Otherwise I'll just start building stuff out now.

**Comment by just-be-dev** [comment]
Maybe we can set aside some time to pair on it? I'll still need to get up to speed on paperclip's setup.
